AWSTemplateFormatVersion: 2010-09-09
Resources:
  LambdaFunction:
    Type: 'AWS::Lambda::Function'
    Properties:
      Code:
        S3Bucket: !Sub '${AWS::StackName}-lambda'
        S3Key: !Sub '${AWS::StackName}.zip'
      FunctionName: !Ref AWS::StackName
      Role: 'arn:aws:iam::501511055678:role/basic-lambda-role'
      Handler: index.main
      Runtime: python3.7
