AWSTemplateFormatVersion: 2010-09-09
Resources:
  TerraformLockDB:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      AttributeDefinitions:
        - AttributeName: LockID
          AttributeType: S
      KeySchema:
        - AttributeName: LockID
          KeyType: HASH
      TableName: !Sub '${AWS::StackName}-lockdb'
      BillingMode: PAY_PER_REQUEST
  TerraformStateStore:
    Type: 'AWS::S3::Bucket'
  PipelineArtifactStore:
    Type: 'AWS::S3::Bucket'
  TerraformBuildProject:
    Type: 'AWS::CodeBuild::Project'
    Properties:
      Name: !Sub '${AWS::StackName}-Run'
      ServiceRole: arn:aws:iam::501511055678:role/service-role/codebuild-Terraform-service-role
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux2-x86_64-standard:3.0
      Source:
        Type: CODEPIPELINE
  TerraformPipeline:
    Type: 'AWS::CodePipeline::Pipeline'
    Properties:
      Name: !Sub '${AWS::StackName}-pipeline'
      ArtifactStore:
        Type: S3
        Location:
          Ref: PipelineArtifactStore
      RoleArn: arn:aws:iam::501511055678:role/service-role/codebuild-Terraform-service-role
      Stages:
        - Name: Source
          Actions:
            - Name: GitHubSource
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Provider: GitHub
                Version: 1
              OutputArtifacts:
                - Name: GitHubArtifact
              Configuration:
                Owner: gmadro
                Repo: terraRepo
                Branch: master
                OAuthToken: "{{resolve:secretsmanager:GitHubAuth:SecretString:GitHubAuth}}"
        - Name: Build
          Actions:
            - Name: TerraformRun
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: 1
              Configuration:
                ProjectName: !Sub ${AWS::StackName}-Run
              InputArtifacts:
                - Name: GitHubArtifact
