AWSTemplateFormatVersion: 2010-09-09
Resources:
  TerraformLockDB:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      AttributeDefinitions:
        - AttributeName: TestId
          AttributeType: S
      KeySchema:
        - AttributeName: TestId
          KeyType: HASH
      TableName: !Sub '${AWS::StackName}-lockdb'
      BillingMode: PAY_PER_REQUEST
  TerraformStateStore:
    Type: 'AWS::S3::Bucket'
    Properties:
      Bucketname: '${AWS::StackName}-statebucket'
