name: Test Workflow

on:
  schedule:
  - cron: "*/10 * * * *"

jobs:
  test1:

    runs-on: ubuntu-latest

    steps:
    - name: Test
      env:
        x1: ${{ secrets.test_secret }}
      run: 
        echo $x1
